/// <summary>
/// All events to be used need to be added to this script.
/// </summary>
#region Event Types enum
public enum EventID
{

    //Level
    EVENT_ON_LEVEL_STARTED,
    EVEN_ON_LEVEL_FINISHED,
    EVENT_ON_LEVEL_EXITED,
    EVENT_RESTART_LEVEL_REQUESTED,

    //Player
    EVENT_ON_PLAYER_WIN,

    //Spot point
    EVENT_ON_SPOTPOINT_CLICKED,
    EVENT_ON_SPOTPOINT_SELECTED,
    EVENT_ON_SPOTPOINT_SELECTION_ENDED,
    EVENT_ON_HIDE_CAN_OCCUPY_GRAPHIC,

    //Goat
    EVENT_ON_GOAT_ONBOARDING_REQUESTED,
    EVENT_ANIMAL_ONBOARDED,
    EVENT_ON_GOAT_TURN,
    EVENT_ON_GOAT_DEAD_POINT_DETECTED,
    EVENT_ON_GOAT_KILLED,


    //Tiger
    EVENT_ON_TIGER_TURN,
    EVENT_ON_TIGER_BLOCKED,
    EVENT_ON_TIGER_UNBLOCKED,

    //Gameplay
    EVENT_ON_SPOT_POINTS_AVAILABLE_TO_OCCUPY,
    EVENT_REQUEST_TO_CHANGE_PLAYER_TURN,
    EVENT_ON_ANIMAL_MOVED,

    //ScreenManager
    EVENT_ON_CHANGE_SCREEN_REQUESTED,
    EVENT_REQUEST_TO_CHANGE_SCREEN_WITH_TRANSITION,
    EVENT_ON_REMOVE_ALL_SCREENS_REQUESTED,
    EVENT_ON_CLOSE_LAST_ADDITIVE_SCREEN,
    EVENT_REQUEST_GENERIC_POPUP_SETUP,
    EVENT_REQUEST_SCREEN_TRANSITION,
    EVENT_REQUEST_GET_CURRENT_SCREEN,
    EVENT_REQUEST_GE_PREVIOUS_SCREEN,


    //Fade Screen
    EVENT_REQEST_FADE_SCREEN_IN,
    EVENT_REQEST_FADE_SCREEN_OUT,
    EVENT_REQUEST_SCREEN_BLINK,
    EVENT_REQUEST_SCREEN_BLOCK,
    EVENT_REQUEST_SCREEN_UNBLOCK,
    EVENT_REQUEST_TO_KILL_TURN_TIMER_TWEENING,

    ////ADS 
    EVENT_ON_SHOW_BANNER_AD_REQUESTED,
    EVENT_ON_HIDE_BANNER_AD_REQUESTED,
    EVENT_ON_SHOW_MREC_AD_REQUESTED,
    EVENT_ON_HIDE_MREC_AD_REQUESTED,
    EVENT_ON_SHOW_INTERSTITIAL_AD_REQUESTED,
    EVENT_ON_SHOW_REWARDED_AD_REQUESTED,
    EVENT_ON_REWARDED_AD_AVAILABILITY_REQUESTED,
    EVENT_ON_INTERSTITIAL_AD_AVAILABILITY_REQUESTED,

    //Ad State
    EVENT_ON_AD_STATE_CHANGED,
}
#endregion